version: "1.0"
info:
  model: int-scaffold
packages:
- name: Riba_GIT_WB_1526_SingleGitProject
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
- name: TPP_services_in_FCS
  gitServerName: rimaSCName
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: rimabarman
  gitBranch: main
- name: Pack_VersionManagement
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
- name: InvoiceProcessing
  gitServerName: rimaSCName
  gitUrl: https://github.com/Mohamed-Naufal-A-IBM/kj_multi-package-test
  gitUsername: rimabarman
  gitBranch: main
- name: PackageInside
  gitServerName: rimaSCName
  gitUrl: https://github.com/Mohamed-Naufal-A-IBM/kj_multi-package-test
  gitUsername: rimabarman
  gitBranch: main
configurationVariables:
  jdbcfunc.SAPTxStore.failFastMode: false
  jdbcfunc.SAPTxStore.connPoolAlias: SAP TxStore Pool
